version: '2'
services:
  mysql:
    build: ./mysql/
    volumes:
    - ./mysql:/var/lib/mysql
  flask:
    build: ./python/
    ports:
    - "5000:5000"
    links:
    - "mysql:mysql"
    volumes:
    - ./python:/workdir
